[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rainfall-gridder"
version = "0.1.3"
description = "Python package for interpolating rainfall data onto a regular grid."
readme = "README.rst"
authors = [
  {name = "Tom Keel", email = "tomkee@ceh.ac.uk"}
]
maintainers = [
  {name = "Tom Keel", email = "tomkee@ceh.ac.uk"}
]
classifiers = [
    "Typing :: Typed",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
]
license = { file = "LICENSE" }
dependencies = [
    "typer",
    "rich",
    "fsspec",
    "s3fs",
    "polars",
    "altair",
    "xarray[complete]",
    "dask",
    "zarr>=3.0.8",
    "matplotlib",
    "hvplot",
    "pyarrow",
    "pydantic",
    "pyproj",
    "rainfallqc>=1.0.0",
    "scipy>=1.17.1",
    "numpy>=2.4.3",
    "scipy-stubs~=1.17.1",
]
requires-python = ">= 3.12"

[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "test" },
    { include-group = "typecheck" },
    { include-group = "docs" },
]
lint = [
    "ruff",
]
test = [
    "coverage",
    "pytest",
]
typecheck = [
    "ty",
]
docs = [
    "sphinx",
    "shibuya>=2025.9.25",
    "sphinx-copybutton",
    "sphinx-design>=0.6.1",
    "sphinx-iconify>=0.2.1",
    "sphinx-autodoc-typehints",
    "sphinx-autobuild",
    "sphinx-contributors>=0.2.7",
    "myst-parser",
    "numpydoc",
]

[project.urls]
bugs = "https://github.com/NERC-CEH/RainfallGridder/issues"
changelog = "https://github.com/NERC-CEH/RainfallGridder/releases"
documentation = "https://nerc-ceh.github.io/RainfallGridder"
homepage = "https://nerc-ceh.github.io/RainfallGridder"

[project.scripts]
rainfall_gridder = "RainfallGridder.cli:app"

[tool.ty]
# All rules are enabled as "error" by default; no need to specify unless overriding.
# Example override: relax a rule for the entire project (uncomment if needed).
# rules.TY015 = "warn"  # For invalid-argument-type, warn instead of error.

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
]

[tool.coverage.run]
branch = true
parallel = true
source = ["src/", "tests/"]

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 50
exclude_also = [
    "if TYPE_CHECKING:",
    "if typing.TYPE_CHECKING:",
    "@overload",
    "@typing.overload",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
    "raise NotImplementedError",
    "\\.\\.\\.",
]

[tool.uv]
package = true
default-groups = ["dev"]
